### PR TITLE
test: Test multiple electron versions

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
I have to say it is a bit of a joke a new major version is released which focuses on `electron>=14`, but it is not tested with it.

So I made some changes so that electron 11-15 is tested. To get electron 12/13 working `contextIsolation` needed to be disabled.

Electron 14/15 is not working yet, I am working on that. I am not sure I will succeed, but I will open a separate PR for that.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Fiendly ping ;)

**Comment by MatthijsBurgh** [comment]
Friendly ping @FedeIlLeone @gyteng @nornagon ;)

**Comment by MatthijsBurgh** [comment]
ping ping ping @miniak @ckerr @FedeIlLeone @gyteng @nornagon

**Comment by VerteDinde** [comment]
Hey @MatthijsBurgh! It looks like this PR is failing tests for Electron 14 and 15 - could you please rebase/fix the tests, and I can get this merged for you? You can ping me directly once that's done 🙂 Thank you for taking the time to add new tests!

**Comment by MatthijsBurgh** [comment]
@VerteDinde I have removed the test for electron 14/15. As I have not yet worked on these.

But CI should succeed now.

**Comment by MatthijsBurgh** [comment]
@VerteDinde Friendly ping ;)

**Comment by MatthijsBurgh** [comment]
@VerteDinde Friendly ping ;)

**Comment by VanDeny** [comment]
Would be really nice if this could have been solved as soon as possible, since it prevents some developers from upgrading to newer versions of Electron itself...

**Comment by MatthijsBurgh** [comment]
@VerteDinde Friendly ping ping ping ;)

**Pull request merged**
