### PR TITLE
fix: prevent checking isDesktopCapturerEnabled, which crashes on electron@26

### PR DESCRIPTION
**Pull request by JuanIrache**

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
I think we still want to check `isDesktopCapturerEnabled` on versions of Electron that still have that method.

E.g. `features.isDesktopCapturerEnabled?.()` I think will do that 👍

**Comment by miniak** [comment]
> I think we still want to check `isDesktopCapturerEnabled` on versions of Electron that still have that method.
> 
> E.g. `features.isDesktopCapturerEnabled?.()` I think will do that 👍

In E26 the desktop capturer is always enabled, so it has to be `if (features.isDesktopCapturerEnabled?.() !== false)`

**Comment by JuanIrache** [comment]
Of course. Should we do it like

`if (!features || !features.isDesktopCapturerEnabled || features.isDesktopCapturerEnabled()) `

To keep the style consistent?

**Review by MarshallOfSound — APPROVED** [review]

**Comment by codebytere** [comment]
Looks like this wasn't quite the right fix for this issue - it still errors when the function isn't defined. When `features` no longer contains `isDesktopCapturerEnabled`, `!features.isDesktopCapturerEnabled` evaluates to true, which then means the conditional checks the third condition: `features.isDesktopCapturerEnabled()` which throws an error:

```
Uncaught TypeError: features.isDesktopCapturerEnabled is not a function
```

**Pull request merged**
